EXTRA_CFLAGS += -I$(KBUILD_SRC)/drivers/media/dvb/dvb-usb/ \
		-I$(KBUILD_SRC)/drivers/media/dvb/dvb-core/ \
		-I$(KBUILD_SRC)/drivers/media/dvb/frontends/ \
		-I$(KBUILD_SRC)/drivers/media/common/tuners \

obj-y := tuner_e4000.c   tuner_fc2580.c   tuner_mt2063.c  \
		tuner_mxl5007t.c tuner_fc0012.c  tuner_max3543.c  \
		tuner_mt2266.c  tuner_tua9001.c

