EXTRA_CFLAGS += -I$(KBUILD_SRC)/drivers/media/dvb/dvb-usb/ \
		-I$(KBUILD_SRC)/drivers/media/dvb/dvb-core/ \
		-I$(KBUILD_SRC)/drivers/media/dvb/frontends/ \
		-I$(KBUILD_SRC)/drivers/media/common/tuners \

obj-y := dtmb_demod_base.o dtmb_nim_base.o \
			demod_rtl2836.o \
			nim_rtl2836_fc2580.o nim.o nim_rtl2836_mxl5007t.o

