EXTRA_CFLAGS += -I$(KBUILD_SRC)/drivers/media/dvb/dvb-usb/ \
		-I$(KBUILD_SRC)/drivers/media/dvb/dvb-core/ \
		-I$(KBUILD_SRC)/drivers/media/dvb/frontends/ \
		-I$(KBUILD_SRC)/drivers/media/common/tuners \

obj-y := dvbt_nim_base.c dvbt_demod_base.c \
				demod_rtl2832.c \
      				nim_rtl2832_fc0012.c   nim_rtl2832_mt2266.c \
				nim_rtl2832_fc2580.c   nim_rtl2832_mxl5007t.c \
				nim_rtl2832_max3543.c  nim_rtl2832_tua9001.c \
				nim_rtl2832_e4000.c  nim_rtl2832_mt2063.c

