EXTRA_CFLAGS += -I$(KBUILD_SRC)/drivers/media/dvb/dvb-usb/ \
		-I$(KBUILD_SRC)/drivers/media/dvb/dvb-core/ \
		-I$(KBUILD_SRC)/drivers/media/dvb/frontends/ \
		-I$(KBUILD_SRC)/drivers/media/common/tuners \


obj-y := qam_demod_base.c qam_nim_base.c \
				demod_rtl2840.c \
				nim_rtl2840_mt2063.c  nim_rtl2840_max3543.c  

